### PR TITLE
Fix typos & improvements

### PR DESCRIPTION
**Pull request by Chocobo1**
* Fix typo
* Fix punctuation
* Remove redundant word

Update: 
* Trim trailing whitespaces

### CODE REVIEW

**Comment by Chocobo1** [comment]
Can't describe my feelings about TravisCI failing just because it has not been hooked up properly. XD

**Comment by kdchang** [comment]
@Chocobo1  Cool. thanks a lot:)

sorry...xD 
不好意思，請教一下像是各單元有自己的範例程式，那這樣是要怎麼樣 hook TravisCI 會比較好呢？謝謝您～

**Comment by Chocobo1** [comment]
Hmmm, I have little to none experience in web dev, so my ideas may not make sense.

Since there are many examples in the repo, one way is to write a shell script for each example, the script contains commands to test/build the example.
And at the root of the repo, there is a root script that invokes the test/build scripts. The root script could be embedded in the `.travis.yml` file.

TravisCI doc: [Building a Node.js project](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#sts=Travis%20CI%20uses%20npm)

And thank you too for writing this amazing book!

**Comment by kdchang** [comment]
@Chocobo1 OK, Cool. Let me try it.

**Pull request merged**
